### ISSUE TITLE
P2P 안정화 작업

### ISSUE THREAD

**Issue by esevan** [sinban04/opel-alpha#36]
- [x] Bluetooth Pairing 자동화 #34 
- [x] Application Permission 획득 자동화 #34 
- [x] WFD 연결 Logic수정 Comment 확인 #34, #35 
- [x] WFD 연결 안정화
